<a href="https://colab.research.google.com/github/Polarbeargo/PySyft/blob/master/examples/tutorials/Part%2012%20-%20Train%20an%20Encrypted%20Neural%20Network%20on%20Encrypted%20Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Part 12: Train an Encrypted NN on Encrypted Data

In this notebook, we're going to use all the techniques we've learned thus far to perform neural network training (and prediction) while both the model and the data are encrypted.

Note that Autograd is not *yet* supported for encrypted variables, thus we'll have to roll our own gradients ourselves. This functionality will be added in the next PySyft version.

Authors:
- Andrew Trask - Twitter: [@iamtrask](https://twitter.com/iamtrask)
- Jason Paumier - Github: [@Jasopaum](https://github.com/Jasopaum)

In [1]:
!pip install syft

     |████████████████████████████████| 194kB 4.8MB/s 
     |████████████████████████████████| 450kB 37.8MB/s 
     |████████████████████████████████| 71kB 24.9MB/s 
     |████████████████████████████████| 1.4MB 36.7MB/s 
     |████████████████████████████████| 389kB 37.8MB/s 
     |████████████████████████████████| 204kB 46.6MB/s 
     |████████████████████████████████| 276kB 35.8MB/s 
     |████████████████████████████████| 51kB 17.8MB/s 
     |████████████████████████████████| 122kB 41.0MB/s 
  Stored in directory: /root/.cache/pip/wheels/ad/9a/f4/3105b5209674ac77fcca7fede95184c62a95df0196888e0e76
  Stored in directory: /root/.cache/pip/wheels/16/27/a1/775c62ddea7bfa62324fd1f65847ed31c55dadb6051481ba3f
Successfully built zstd pyyaml
  Found existing installation: PyYAML 3.13
    Uninstalling PyYAML-3.13:
      Successfully uninstalled PyYAML-3.13


# Step 1: Create Workers and Toy Data

In [0]:
import torch
import torch.optim as optim

import syft as sy

In [0]:
# Set everything up
hook = sy.TorchHook(torch) 

alice = sy.VirtualWorker(id="alice", hook=hook)
bob = sy.VirtualWorker(id="bob", hook=hook)
james = sy.VirtualWorker(id="james", hook=hook)

In [0]:
# Create our dataset

data = torch.Tensor([[0., 0.], [0., 1.], [1., 0.], [1., 1.]])
target = torch.Tensor([[0.], [0.], [1.], [1.]])

In [0]:
# Create our model
# We use a small linear model: M.X = y
# where M is the mdoel, X is the data, and y the prediction

model = torch.Tensor([[0.], [0.]])
learning_rate = 0.1

# Step 2: Encrypt the Model and Data

Encryption here comes in two steps. Since Secure Multi-Party Computation only works on Longs, in order to operate over numbers with decimal points (such as weights and activations), we need to encode all of our numbers using Fixed Precision, which will give us several bits of floating point precision. We do this by calling .fix_precision().

We can then call .share() as we have for other demos, which will encrypt all of the values by sharing them between Alice and Bob.

In [0]:
# We encode everything
data_enc = data.fix_precision().share(alice, bob, crypto_provider=james)
target_enc = target.fix_precision().share(alice, bob, crypto_provider=james)
model_enc = model.fix_precision().share(alice, bob, crypto_provider=james)

# For now, we also need to encode the learning rate but this will change in the near future
learning_rate_fp = (
    torch.Tensor([learning_rate])
    .fix_precision()
    .share(alice, bob, crypto_provider=james)
)

# Step 3: Train

And now we can train using simple tensor logic. Note that autograd is not yet supported (but it will be in the Torch 1.0 refactor which you can [watch here](https://github.com/OpenMined/PySyft/issues/1587)).

In [7]:
for i in range(20):
    # Use the model to predict
    pred = data_enc.matmul(model_enc)
    # How much is the model wrong
    err = pred - target_enc
    # Compute gradient descent step
    update = data_enc.t().matmul(err)
    # Apply the gradient descent step
    model_enc = model_enc - update * learning_rate_fp
    
    loss = err.get().abs().sum().float_prec()
    print(loss) 

tensor([2.])
tensor([1.6000])
tensor([1.3000])
tensor([1.0720])
tensor([0.8980])
tensor([0.7600])
tensor([0.6500])
tensor([0.5620])
tensor([0.4880])
tensor([0.4280])
tensor([0.3760])
tensor([0.3320])
tensor([0.2940])
tensor([0.2620])
tensor([0.2340])
tensor([0.2100])
tensor([0.1880])
tensor([0.1680])
tensor([0.1520])
tensor([0.1360])


The loss indeed decreased.

We can also verify that the model is close to what we could have expected (the task was to output the value of the first dimension of the input).

In [8]:
model_enc.get().float_precision()

tensor([[0.9390],
        [0.0600]])

# Congratulations!!! - Time to Join the Community!

Congratulations on completing this notebook tutorial! If you enjoyed this and would like to join the movement toward privacy preserving, decentralized ownership of AI and the AI supply chain (data), you can do so in the following ways!

### Star PySyft on Github

The easiest way to help our community is just by starring the Repos! This helps raise awareness of the cool tools we're building.

- [Star PySyft](https://github.com/OpenMined/PySyft)

### Join our Slack!

The best way to keep up to date on the latest advancements is to join our community! You can do so by filling out the form at [http://slack.openmined.org](http://slack.openmined.org)

### Join a Code Project!

The best way to contribute to our community is to become a code contributor! At any time you can go to PySyft Github Issues page and filter for "Projects". This will show you all the top level Tickets giving an overview of what projects you can join! If you don't want to join a project, but you would like to do a bit of coding, you can also look for more "one off" mini-projects by searching for github issues marked "good first issue".

- [PySyft Projects](https://github.com/OpenMined/PySyft/issues?q=is%3Aopen+is%3Aissue+label%3AProject)
- [Good First Issue Tickets](https://github.com/OpenMined/PySyft/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22)

### Donate

If you don't have time to contribute to our codebase, but would still like to lend support, you can also become a Backer on our Open Collective. All donations go toward our web hosting and other community expenses such as hackathons and meetups!

[OpenMined's Open Collective Page](https://opencollective.com/openmined)